name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: |
        mvn clean compile package -pl core,bukkit,velocity -am
        
    - name: Create release directory
      run: |
        mkdir -p release
        
    - name: Copy artifacts
      run: |
        cp bukkit/target/*.jar release/ 2>/dev/null || echo "No bukkit artifacts found"
        cp velocity/target/*.jar release/ 2>/dev/null || echo "No velocity artifacts found"
        
    - name: List release files
      run: ls -la release/
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: plugin-jars
        path: release/*.jar
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: release/*.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}